name: Approve Lock

on: [push]

env:
  File_Change: steps.file_changes.outputs.changes

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check File Changes
        id: file_changes
        run: 'echo "::set-output name=changes::$(git --no-pager diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})"'

      - name: test
        if: &{{ env.File_Change.includes('com/example/github_action_test_test/MainActivity2') }}
        run: |
          -f Hello!

#        with:
#          script: |
#            const filesChanged = ${{ steps.file_changes.outputs.changes }}
#            const lockApproved = filesChanged.includes('com/example/github_action_test_test/MainActivity')
#            if (lockApproved) {
#              console.log('File changes detected. Approve lock activated.')
#              const { owner, repo, number } = context.issue
#              github.pulls.createReview({
#                owner: owner,
#                repo: repo,
#                pull_number: number,
#                event: 'REQUEST_CHANGES',
#                body: 'Approval locked due to file changes.'
#              })
#            } else {
#              console.log('No file changes detected. Skipping approve lock.')
#            }