name: Approve Lock

on: [push]

jobs:
  check-file-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check File Changes
        id: file_changes
        run: 'echo "::set-output name=changes::$(git --no-pager diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})"'

#      - name: Approve Lock
#        uses: actions/github-script@v4

      - name: test
        run: |
          echo Hello World!